name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Node Modules
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Sync Capacitor Android
        run: npx cap sync android

      - name : Make Grande Executable
        run: chmod +x android/gradlew

      - name: Build APK (Android)
        working-directory: ./android
        run: ./gradlew assembleDebug  --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RPGM-Player-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
